server:
  port: 8085

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/weatherapi
    username: postgres
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600000
  issuer: weather
limits:
  user:
    bucketCapacity: 3
    refillGreedyTokens: 1
    refillGreedyDurationSeconds: 10
  admin:
    bucketCapacity: 10
    refillGreedyTokens: 5
    refillGreedyDurationSeconds: 5

---

spring:
  profiles: test
  r2dbc:
    url: r2dbc:tc:postgresql:///testdb?TC_IMAGE_TAG=14-alpine







